R = require
R "settings"
R "keymaps"
R "colorscheme"
R "plugins.init"
R "plugins.nvim-tree"
R "plugins.autosave"
R "plugins.dart-vim-plugin"
R "plugins.nvim-lspconfig"
R "plugins.lspsaga"
R "plugins.rainbow"
R "plugins.lualine"
R "plugins.statusline"
R "plugins.lazygit"
R "plugins.syntastic"
R "plugins.nvim-colorizer"
R "plugins.telescope"
R "plugins.flutter-tools"

