R = require
R "settings"
R "keymaps"
R "colorscheme"
R "plugins.init"
R "plugins.nvim-tree"
R "plugins.nvim-treesitter"
R "plugins.nvim-cmp"
R "plugins.indent-blankline"
R "plugins.autosave"
R "plugins.format"
R "plugins.dart-vim-plugin"
R "plugins.nvim-lspconfig"
R "plugins.lspsaga"
R "plugins.rainbow"
R "plugins.barbar"
R "plugins.statusline"
R "plugins.syntastic"
R "plugins.nvim-colorizer"
R "plugins.telescope"
R "plugins.flutter-tools"

